services:
  db:
    image: postgres:15-alpine
    container_name: fueleu-db
    environment:
      POSTGRES_USER: fueleu
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: fueleu
    ports:
      - "5432:5432"   # if busy, change to "5433:5432"
    volumes:
      - fueleu_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fueleu -d fueleu"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  fueleu_pg:
